-- region *.lua
-- Date
-- 此文件由[BabeLua]插件自动生成
local UplevelCell = class("UplevelCell", cc.Node)
local TYPE_FRIST_1 = 1
local TYPE_FRIST_2 = 2
local TYPE_SPIN_1 = 3
local TYPE_SPIN_2 = 4
local TYPE_SPIN_3 = 5

function UplevelCell:ctor(data)
    if data.type == TYPE_FRIST_1 then
        self:createImg("uplevel/levelup_slots_levelup.png")
    elseif data.type == TYPE_FRIST_2 then
        self:createImg("uplevel/levelup_starup.png")
    elseif data.type == TYPE_SPIN_1 then
        self:createCoins(data.value)
    elseif data.type == TYPE_SPIN_2 then
        self:createAll(data.value)
    elseif data.type == TYPE_SPIN_3 then
        if data.value==1 then
            self:createOther()
        elseif data.value==2 then
            self:createImg("uplevel/levelup_lottoBronze.png")
        elseif data.value==3 then
            self:createImg("uplevel/levelup_lottoSilver.png")
        elseif data.value==4 then
            self:createImg("uplevel/levelup_lottoGold.png")
        end
    end
end

function UplevelCell:createImg(path)
    local img_1 = ccui.ImageView:create()
    img_1:ignoreContentAdaptWithSize(false)
    img_1:loadTexture(path, 0)
    img_1:setLayoutComponentEnabled(true)
    img_1:setName("img_1")
    img_1:setTag(146)
    img_1:setCascadeColorEnabled(true)
    img_1:setCascadeOpacityEnabled(true)
    local layout = ccui.LayoutComponent:bindLayoutComponent(img_1)
    layout:setPositionPercentXEnabled(true)
    layout:setPositionPercentYEnabled(true)

    layout:setSize(img_1:getContentSize())
    layout:setLeftMargin(-81.5000)
    layout:setRightMargin(-81.5000)
    layout:setTopMargin(-52.5000)
    layout:setBottomMargin(-52.5000)
    self:addChild(img_1)
end

function UplevelCell:createCoins(num)
    -- Create Panel_1
    local Panel_1 = ccui.Layout:create()
    Panel_1:ignoreContentAdaptWithSize(false)
    Panel_1:setClippingEnabled(false)
    Panel_1:setBackGroundColorOpacity(102)
    Panel_1:setTouchEnabled(true);
    Panel_1:setLayoutComponentEnabled(true)
    Panel_1:setName("Panel_1")
    Panel_1:setTag(43)
    Panel_1:setCascadeColorEnabled(true)
    Panel_1:setCascadeOpacityEnabled(true)
    Panel_1:setAnchorPoint(0.5000, 0.5000)
    local layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
    layout:setSize( { width = 200.0000, height = 200.0000 })
    layout:setLeftMargin(-100.0000)
    layout:setRightMargin(-100.0000)
    layout:setTopMargin(-100.0000)
    layout:setBottomMargin(-100.0000)
    self:addChild(Panel_1)

    -- Create Image_1
    local Image_1 = ccui.ImageView:create()
    Image_1:ignoreContentAdaptWithSize(false)
    Image_1:loadTexture("uplevel/levelup_chips.png", 0)
    Image_1:setLayoutComponentEnabled(true)
    Image_1:setName("Image_1")
    Image_1:setTag(42)
    Image_1:setCascadeColorEnabled(true)
    Image_1:setCascadeOpacityEnabled(true)
    Image_1:setPosition(100.0000, 100.0000)
    layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
    layout:setPositionPercentX(0.5000)
    layout:setPositionPercentY(0.5000)
    layout:setPercentWidth(0.6300)
    layout:setPercentHeight(0.7100)
    layout:setSize( { width = 126.0000, height = 142.0000 })
    layout:setLeftMargin(37.0000)
    layout:setRightMargin(37.0000)
    layout:setTopMargin(29.0000)
    layout:setBottomMargin(29.0000)
    Panel_1:addChild(Image_1)

    -- Create Text_4
    local Text_4 = ccui.Text:create()
    Text_4:ignoreContentAdaptWithSize(true)
    Text_4:setTextAreaSize( { width = 0, height = 0 })
    Text_4:setFontName("font/FZKTJW.TTF")
    Text_4:setFontSize(36)
    Text_4:setString(num)
    Text_4:setLayoutComponentEnabled(true)
    Text_4:setName("Text_4")
    Text_4:setTag(44)
    Text_4:setCascadeColorEnabled(true)
    Text_4:setCascadeOpacityEnabled(true)
    Text_4:setAnchorPoint(1.0000, 0.5000)
    Text_4:setPosition(86.8778, 40.1778)
    Text_4:setTextColor( { r = 0, g = 0, b = 0 })
    layout = ccui.LayoutComponent:bindLayoutComponent(Text_4)
    layout:setPositionPercentX(0.4344)
    layout:setPositionPercentY(0.2009)
    layout:setPercentWidth(0.1800)
    layout:setPercentHeight(0.1950)
    layout:setSize( { width = 36.0000, height = 39.0000 })
    layout:setLeftMargin(50.8778)
    layout:setRightMargin(113.1222)
    layout:setTopMargin(140.3223)
    layout:setBottomMargin(20.6778)
    Panel_1:addChild(Text_4)
end

function UplevelCell:createAll(num)
    local Text_1 = ccui.Text:create()
    Text_1:ignoreContentAdaptWithSize(true)
    Text_1:setTextAreaSize( { width = 0, height = 0 })
    Text_1:setFontName("font/FZKTJW.TTF")
    Text_1:setFontSize(100)
    Text_1:setString("X" .. num)
    Text_1:enableShadow( { r = 110, g = 110, b = 110, a = 255 }, { width = 2, height = - 2 }, 0)
    Text_1:enableOutline( { r = 191, g = 191, b = 191, a = 255 }, 1)
    Text_1:setLayoutComponentEnabled(true)
    Text_1:setName("Text_1")
    Text_1:setTag(147)
    Text_1:setCascadeColorEnabled(true)
    Text_1:setCascadeOpacityEnabled(true)
    Text_1:setTextColor( { r = 223, g = 181, b = 50 })
    local layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
    layout:setSize( { width = 125.0000, height = 111.0000 })
    layout:setLeftMargin(-62.5000)
    layout:setRightMargin(-62.5000)
    layout:setTopMargin(-55.5000)
    layout:setBottomMargin(-55.5000)
    self:addChild(Text_1)
end

function UplevelCell:createOther()
    -- Create Panel_2
    local time = "5分钟"
    local Panel_2 = ccui.Layout:create()
    Panel_2:ignoreContentAdaptWithSize(false)
    Panel_2:setClippingEnabled(false)
    Panel_2:setBackGroundColorOpacity(102)
    Panel_2:setTouchEnabled(true);
    Panel_2:setLayoutComponentEnabled(true)
    Panel_2:setName("Panel_2")
    Panel_2:setTag(149)
    Panel_2:setCascadeColorEnabled(true)
    Panel_2:setCascadeOpacityEnabled(true)
    Panel_2:setAnchorPoint(0.5000, 0.5000)
    local layout = ccui.LayoutComponent:bindLayoutComponent(Panel_2)
    layout:setSize( { width = 200.0000, height = 200.0000 })
    layout:setLeftMargin(-100.0000)
    layout:setRightMargin(-100.0000)
    layout:setTopMargin(-100.0000)
    layout:setBottomMargin(-100.0000)
    self:addChild(Panel_2)

    -- Create img_2
    local img_2 = ccui.ImageView:create()
    img_2:ignoreContentAdaptWithSize(false)
    img_2:loadTexture("uplevel/levelup_XP.png", 0)
    img_2:setLayoutComponentEnabled(true)
    img_2:setName("img_2")
    img_2:setTag(148)
    img_2:setCascadeColorEnabled(true)
    img_2:setCascadeOpacityEnabled(true)
    img_2:setPosition(100.0000, 121.2400)
    layout = ccui.LayoutComponent:bindLayoutComponent(img_2)
    layout:setPositionPercentXEnabled(true)
    layout:setPositionPercentYEnabled(true)
    layout:setPositionPercentX(0.5000)
    layout:setPositionPercentY(0.6062)
    layout:setPercentWidth(0.8900)
    layout:setPercentHeight(0.6650)
    layout:setSize( { width = 178.0000, height = 133.0000 })
    layout:setLeftMargin(11.0000)
    layout:setRightMargin(11.0000)
    layout:setTopMargin(12.2600)
    layout:setBottomMargin(54.7400)
    Panel_2:addChild(img_2)

    -- Create Text_2
    local Text_2 = ccui.Text:create()
    Text_2:ignoreContentAdaptWithSize(true)
    Text_2:setTextAreaSize( { width = 0, height = 0 })
    Text_2:setFontName("font/FZKTJW.TTF")
    Text_2:setFontSize(30)
    Text_2:setString([[5M]])
    Text_2:enableShadow( { r = 110, g = 110, b = 110, a = 255 }, { width = 2, height = - 2 }, 0)
    Text_2:setLayoutComponentEnabled(true)
    Text_2:setName("Text_2")
    Text_2:setTag(150)
    Text_2:setCascadeColorEnabled(true)
    Text_2:setCascadeOpacityEnabled(true)
    Text_2:setPosition(111.3586, 31.5514)
    layout = ccui.LayoutComponent:bindLayoutComponent(Text_2)
    layout:setPositionPercentX(0.6256)
    layout:setPositionPercentY(0.2372)
    layout:setPercentWidth(0.2472)
    layout:setPercentHeight(0.2481)
    layout:setSize( { width = 44.0000, height = 33.0000 })
    layout:setLeftMargin(89.3586)
    layout:setRightMargin(44.6414)
    layout:setTopMargin(84.9486)
    layout:setBottomMargin(15.0514)
    img_2:addChild(Text_2)

    -- Create Text_3
    local Text_3 = ccui.Text:create()
    Text_3:ignoreContentAdaptWithSize(true)
    Text_3:setTextAreaSize( { width = 0, height = 0 })
    Text_3:setFontName("font/FZKTJW.TTF")
    Text_3:setFontSize(25)
    Text_3:setString("xp2倍加速" .. "\n" .. "5分钟")
    Text_3:enableOutline( { r = 0, g = 0, b = 0, a = 255 }, 1)
    Text_3:setLayoutComponentEnabled(true)
    Text_3:setName("Text_3")
    Text_3:setTag(151)
    Text_3:setCascadeColorEnabled(true)
    Text_3:setCascadeOpacityEnabled(true)
    Text_3:setPosition(87.2309, -19.4878)
    Text_3:setTextColor( { r = 0, g = 0, b = 0 })
    layout = ccui.LayoutComponent:bindLayoutComponent(Text_3)
    layout:setPositionPercentX(0.4901)
    layout:setPositionPercentY(-0.1465)
    layout:setPercentWidth(0.6517)
    layout:setPercentHeight(0.4361)
    layout:setSize( { width = 116.0000, height = 58.0000 })
    layout:setLeftMargin(29.2309)
    layout:setRightMargin(32.7691)
    layout:setTopMargin(123.4878)
    layout:setBottomMargin(-48.4878)
    img_2:addChild(Text_3)
end

return UplevelCell
-- endregion
